### ISSUE TITLE
Ability to create multiple surveys

### ISSUE THREAD

**Issue by mbajwa** [aamir-poswal/SurveyTrackerApp#1]
The App should allow the user to create multiple surveys

**Comment by aamir-poswal** [comment]
General Comment:
Have you tried tools like Balsamiq Mockups (its free) for mockups? Please add mark up where possible.

Some people also use https://jetstrap.com/ (though it is a paid).

**Comment by mbajwa** [comment]
Yes, ive looked into Balsamiq. Its a good tool indeed. We are also looking into https://www.lucidchart.com

we will get you some mockups.. sometimes. we just end up creating mockups by Hand :)

**Comment by aamir-poswal** [comment]
mackups by hand are also very useful, as visual representation is always helpful.

**Comment by fherrick** [comment]
yes - able to create multiple surveys
![landing page](https://cloud.githubusercontent.com/assets/11509212/6931845/d1aa469a-d7c6-11e4-8031-7789f6017ed8.png)

**Comment by fherrick** [comment]
survey crashes when testing the direct url

**Comment by aamir-poswal** [comment]
Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
This works, no error. This can be closed but I don't have the comment close button since I didn't open this task
