### ISSUE TITLE
Ability to schedule the survey to close

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#10]
Please create an option at the survey level to automatically close the survey per a scheduled time.
A check box the survey creator can select.

This option can be set on the new survey page - https://github.com/aamir-poswal/SurveyTrackerApp/issues/8

sample image - 

![close survey](https://cloud.githubusercontent.com/assets/11509212/6676914/b5dd0388-cbe8-11e4-8b29-6ecb1c637913.png)

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15)

**Comment by fherrick** [comment]
@aamir-poswal 

Can you add am/pm and time zone to the close survey controls.

![schedule](https://cloud.githubusercontent.com/assets/11509212/7009941/c6961ee2-dc52-11e4-8365-5d1f2d2a33b4.png)

**Comment by aamir-poswal** [comment]
@fherrick, Please verify on dev, and share your feedback.
