### ISSUE TITLE
Ability to block repeat voting

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#11]
Please create an option at the survey level to block repeat voting.

This can be done by a cookie in the browser that will expire after a selected period of time.
The cookie will track when the user has answered a poll/survey and will give a message that user has already voted if they attempt to answer a survey/poll a second time.

Message displayed 'Thank you, we have already counted your answer.'

Options:

1. Don't block repeat voting - this can be default setting, allows participants to vote repeatedly.
2. Block by Cookie - creator will choose an expiration date for the cookie/block. Which will allow voters to vote again after the block.
3. Block by Cookie & IP - we don't need this option at this time.

sample image -

![block by cookie](https://cloud.githubusercontent.com/assets/11509212/6677565/8466b4b0-cbee-11e4-8bde-aab4b41234b2.png)

![block by cookie](https://cloud.githubusercontent.com/assets/11509212/6677665/6a95859c-cbef-11e4-89da-677a2c37ca05.png)

![message](https://cloud.githubusercontent.com/assets/11509212/6677625/0fa626c8-cbef-11e4-8a37-fc5b017e40f1.png)

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15)

**Comment by aamir-poswal** [comment]
@fherrick, 

Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
Survey settings enabled - block by cookie

I was able to to vote twice using this link in IE - http://192.168.1.8:80/survey/test-repeat-voting
I should have been blocked from doing the second vote.

It blocked second vote in Chrome after I submitted first vote, closed browser and then went to link 2nd time. http://192.168.1.8/survey/test-repeat-voting

**Comment by fherrick** [comment]
Also getting we have already counted your vote on a completely new survey - http://192.168.1.8/survey/test-editing-ratings

Cookie to block repeat voting needs to be tied to one survey, not all of them.
![2](https://cloud.githubusercontent.com/assets/11509212/7359534/40f61c94-ecf4-11e4-8064-8a42e2f21718.png)


just created this survey to test editing rankings.

**Comment by fherrick** [comment]
Seems to be working now
