### ISSUE TITLE
Ability to randomize the questions within the survey

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#13]
Please create an option at the survey level or page level to randomize the questions.

This can be a check box the survey creator can select.

Sample image

![random](https://cloud.githubusercontent.com/assets/11509212/6677887/528c5b2c-cbf1-11e4-87e8-c06971cbdb5e.png)

**Comment by fherrick** [comment]
Survey not retaining when I  select the check box for randomize question on the page.

Before
![random](https://cloud.githubusercontent.com/assets/11509212/6931800/4f81f636-d7c6-11e4-9397-4165884895b0.png)

I selected the check box to randomize questions and looked a preview - which worked.
![random1](https://cloud.githubusercontent.com/assets/11509212/6931807/5ed7e6d6-d7c6-11e4-89ac-a0b4ae102930.png)

But when I went to the url for the survey - the questions were not random
![url](https://cloud.githubusercontent.com/assets/11509212/6931811/6cb58876-d7c6-11e4-8ae1-335b70ef0d09.png)

Build Survey for Survey show that the box for randomize questions is unchecked. It didn't save my selection.
![1](https://cloud.githubusercontent.com/assets/11509212/6931823/9956bdb4-d7c6-11e4-81b9-9a2141b215e9.png)

**Comment by aamir-poswal** [comment]
@fherrick Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
Random still doesn't appear to be working. Selected randomize on multiple choice and then checked preview and the direct url for survey. Questions were in same order as they were in create/build survey.

Build survey:
![mc2](https://cloud.githubusercontent.com/assets/11509212/7009458/43248d30-dc4f-11e4-87b3-5583e52868fb.png)

Direct url:
![random3](https://cloud.githubusercontent.com/assets/11509212/7009456/42ef8b76-dc4f-11e4-930f-5ba1b7ee2263.png)

preview:
![random2](https://cloud.githubusercontent.com/assets/11509212/7009457/42f029f0-dc4f-11e4-99a6-379b5ebeef41.png)

**Comment by aamir-poswal** [comment]
@fherrick, Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
This is working now.
