### ISSUE TITLE
Ability to add an image to a question

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#17]
Please create an option at the question level to add an attachment

samples:

![scale1](https://cloud.githubusercontent.com/assets/11509212/6678155/262e5118-cbf4-11e4-92e1-96f4cb66472b.png)

![matrix rating](https://cloud.githubusercontent.com/assets/11509212/6678143/079a04b8-cbf4-11e4-9249-207d0c4c968e.png)

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15)

**Comment by aamir-poswal** [comment]
@fherrick, 

Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
I added this image  and it was stretched. Is there a way to stop that or what should be the size of the image. 
![butterfly](https://cloud.githubusercontent.com/assets/11509212/7355614/e0fdd4a6-ecd7-11e4-9622-4c46e21e65e2.jpg)

![pic](https://cloud.githubusercontent.com/assets/11509212/7355709/7de93f4e-ecd8-11e4-935c-033c1e667407.png)

this is what I would expect to see. 
![1](https://cloud.githubusercontent.com/assets/11509212/7356325/309d760c-ecdc-11e4-876d-a3e3f125e4ec.png)

**Comment by fherrick** [comment]
Looks much better

![image to question](https://cloud.githubusercontent.com/assets/11509212/7505886/e76b0a5c-f40c-11e4-9dbb-c4acb342c6a8.png)
