### ISSUE TITLE
Create Landing page

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#2]
The landing page is the entry page for survey creators - roles of admin and survey manager.
Landing page should be a simple list of all the surveys that have been created. Information for each survey is listed below.
  
  -title of survey
  -date survey created/modified
  -user that created survey

Roles 
- Admins will see all surveys
-Survey Managers will see only the surveys they have created/edited.

Samples of Landing Pages - doesn't have to be exactly like this.
![landing page](https://cloud.githubusercontent.com/assets/11509212/6675621/36773edc-cbdf-11e4-814b-06794c72eb82.jpg)
![landing page1](https://cloud.githubusercontent.com/assets/11509212/6675729/ea61d092-cbdf-11e4-867f-61c69c854b39.jpg)

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15)

**Comment by fherrick** [comment]
![landing page](https://cloud.githubusercontent.com/assets/11509212/6908794/f790b1c8-d6f4-11e4-917c-413b8b0071e9.png)

**Comment by fherrick** [comment]
Thank you for adding the preview and collect response as a tab in the create/build survey. Keep these here. Can you please add the collect response & preview back to the landing page. We would like to see these in both places - on the landing page in line with the  survey and within the create/build survey.

add back collect responses & preview to landing page
![landing page](https://cloud.githubusercontent.com/assets/11509212/6931706/175d63ea-d7c5-11e4-8e78-752e6a57807f.png)

Keep collect response & preview here as well. 
![1](https://cloud.githubusercontent.com/assets/11509212/6931700/06c094bc-d7c5-11e4-869d-3c34c2736053.png)

**Comment by aamir-poswal** [comment]
@fherrick Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
Done

![error](https://cloud.githubusercontent.com/assets/11509212/7008869/0eac9f6a-dc4b-11e4-9f38-f827a5a7f2dd.png)
