### ISSUE TITLE
provide direct link to survey

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#20]
Survey will provide one url/link that can be sent to users.

sample

![link](https://cloud.githubusercontent.com/assets/11509212/6678258/a5694644-cbf5-11e4-9201-0e4f77b60cd7.png)

![link1](https://cloud.githubusercontent.com/assets/11509212/6678262/bed819b6-cbf5-11e4-972f-f38135034272.png)

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15)

**Comment by fherrick** [comment]
can we also add a link to this in the create/build survey as a tab after other survey options.

![direct link](https://cloud.githubusercontent.com/assets/11509212/6908728/3cd8f5f2-d6f4-11e4-839e-a792250d11e4.png)

**Comment by aamir-poswal** [comment]
Please verify, and share your feedback.

**Comment by fherrick** [comment]
Thank you for adding the link in the create/build survey. Keep this here, can you please add the collect response back to the landing page. We would like to see this in both places - on the landing page in line with the  survey and within the create/build survey.

Keep this -
![landing page](https://cloud.githubusercontent.com/assets/11509212/6931706/175d63ea-d7c5-11e4-8e78-752e6a57807f.png)

![1](https://cloud.githubusercontent.com/assets/11509212/6931700/06c094bc-d7c5-11e4-869d-3c34c2736053.png)

**Comment by fherrick** [comment]
Yes, this is done

![2](https://cloud.githubusercontent.com/assets/11509212/7009873/4d201a90-dc52-11e4-95fd-e0f8bfd7001a.png)
