### ISSUE TITLE
Create Preview/Deploy Survey page

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#23]
Create Preview/Deploy Survey page

This would be the 3rd screen a user would see when they are creating a new survey.
This is where the creator will preview the survey

Please incorporate these elements

- preview of survey as user would view it.
- display direct link for survey
- display the embed code for websites

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15) (for now you can skip the embed code requirement)

**Comment by fherrick** [comment]
Please add Preview to the tab under create/build survey
![3](https://cloud.githubusercontent.com/assets/11509212/6908384/8f4faefa-d6f1-11e4-9cf9-5c1c64933c51.png)

**Comment by fherrick** [comment]
Preview for rtrt survey didn't work

![preview](https://cloud.githubusercontent.com/assets/11509212/6908704/087cebba-d6f4-11e4-8f3c-d2801815dce9.png)
![preview 2](https://cloud.githubusercontent.com/assets/11509212/6908713/1c08a8b8-d6f4-11e4-820b-b2d725531653.png)

**Comment by aamir-poswal** [comment]
Please verify, and share your feedback.

**Comment by fherrick** [comment]
preview works now

![1](https://cloud.githubusercontent.com/assets/11509212/6931660/b96962c0-d7c4-11e4-8c34-fd521fd9eb8b.png)
