### ISSUE TITLE
Add survey name as title to the survey

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#24]
Please add survey name as a title to the survey

![title](https://cloud.githubusercontent.com/assets/11509212/6908846/5948b9d8-d6f5-11e4-8471-7353c51516a5.png)

**Comment by aamir-poswal** [comment]
Please verify, and share your feedback.

**Comment by fherrick** [comment]
title header has been added

![2](https://cloud.githubusercontent.com/assets/11509212/6931640/7b72837a-d7c4-11e4-837e-8875a591ba47.png)
![1](https://cloud.githubusercontent.com/assets/11509212/6931641/7b7761ec-d7c4-11e4-8a41-e44623dedcac.png)
