### ISSUE TITLE
custom message in survey from direct  url

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#25]
The custom start message should appear at the beginning of the survey. Not able to see message after survey is completed. Got an error

![1](https://cloud.githubusercontent.com/assets/11509212/6932066/3ef3d69c-d7c9-11e4-951e-8116e379afad.png)

![2](https://cloud.githubusercontent.com/assets/11509212/6932067/421d3912-d7c9-11e4-9970-1f3d4b5043eb.png)

![error](https://cloud.githubusercontent.com/assets/11509212/6932080/658ccfca-d7c9-11e4-8a09-ddc9cb2953d0.png)

**Comment by aamir-poswal** [comment]
Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
Error message is fixed and start message is displayed at beginning of survey.
![tf direct url](https://cloud.githubusercontent.com/assets/11509212/7009042/6b2f6046-dc4c-11e4-94b5-4801725eb4be.png)
![1](https://cloud.githubusercontent.com/assets/11509212/7009043/6b2f6a64-dc4c-11e4-8231-7b8ce1c3472f.png)
