### ISSUE TITLE
url giving error

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#27]
I’m not able to test/review tasks. I keep getting an error when I go to this url - http://localhost/SurveyTakerApp  on the server ITDEV01.
Is there a different url I should be using?

![error](https://cloud.githubusercontent.com/assets/11509212/7008655/ab8bcc04-dc49-11e4-8e05-637d1b9f41b9.png)

**Comment by aamir-poswal** [comment]
Please try testing with.

http://localhost/

and share your experience.

**Comment by fherrick** [comment]
that worked
