### ISSUE TITLE
Please change text

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#28]
@aamir-poswal 

Please change text under rating question from 'include a note false' to 'Include a Note'

![rankq](https://cloud.githubusercontent.com/assets/11509212/7010550/e99f38d4-dc56-11e4-81cf-442f11499d41.png)

**Comment by aamir-poswal** [comment]
@fherrick, Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
Yes, updated. Thanks

![1](https://cloud.githubusercontent.com/assets/11509212/7079537/615eb7d4-deda-11e4-9fc7-ce8be9e94b8d.png)
