### ISSUE TITLE
There is no progress bar indicator in survey

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#29]
There is no progress bar indicator in survey

I selected this option in the survey.

![1](https://cloud.githubusercontent.com/assets/11509212/7079669/f63e6b50-dedb-11e4-9fc6-db3590c53257.png)

Actual survey
![1](https://cloud.githubusercontent.com/assets/11509212/7079682/2fc92fe0-dedc-11e4-9bfc-0999a821b4da.png)
![2](https://cloud.githubusercontent.com/assets/11509212/7079685/33a819a0-dedc-11e4-830d-dc55de6efbe9.png)

**Comment by aamir-poswal** [comment]
@fherrick, 

Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
I see a progress indicator bar now, but it doesn't go to 100%. It should go to 100% when the last question is answered

![progress2](https://cloud.githubusercontent.com/assets/11509212/7355352/0fa6ae92-ecd6-11e4-9519-ea613fdb00fa.png)
![progress](https://cloud.githubusercontent.com/assets/11509212/7355353/0fb7c43e-ecd6-11e4-8cc7-84077566b697.png)

**Comment by aamir-poswal** [comment]
@fherrick,

I have implemented it based on following logic. Please correct me if I am wrong.

(questionAnswered <b>/</b> TotalQuestion)*100

**Comment by fherrick** [comment]
Now this looks corrects.
![indicator](https://cloud.githubusercontent.com/assets/11509212/7505874/ba089b56-f40c-11e4-95a6-dd8cb45165a2.png)
