### ISSUE TITLE
Add close/open toggle to survey list/menu

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#30]
Pelase add  a close/open toggle to survey list/menu.

We need to be able to manually close a survey and have the ability to reopen the survey as well. Thanks

**Comment by aamir-poswal** [comment]
@fherrick, 

Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
I closed the survey and then tried the url for the survey I closed

![1](https://cloud.githubusercontent.com/assets/11509212/7355323/fd4d3504-ecd5-11e4-80ea-028dd61d9793.png)
Got this error message - 
![error](https://cloud.githubusercontent.com/assets/11509212/7355304/e52a9f20-ecd5-11e4-8865-a5a5c35a5783.png)


Can we see a message that says 'This survey has been closed'

**Comment by fherrick** [comment]
close/open works. 

New ticket to change message - https://github.com/aamir-poswal/SurveyTrackerApp/issues/34
