### ISSUE TITLE
change url to not display localhost:2600

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#31]
change url to not display localhost:2600

http://localhost:2600/survey/test-survey-4-7-2015   - for example

When we share the survey url we don't want users to be able to get to the server/survey main page.

**Comment by aamir-poswal** [comment]
@fherrick, 
it is not possible to restrict access without implementing user authentication/authroization module.

**Comment by fherrick** [comment]
We know about the security, that oks.

We just don't want to expose the actual server name.

For instance when I share the survey internally this is the url - http://192.168.1.8:80/survey/it-service-quality

its showing the actual ip address. We would like staff to not see the ip address and would like them to see something else. Can you display something else other than 192.168.1.8:80?

**Comment by aamir-poswal** [comment]
@fherrick, 

Please verify, and share your feedback.

**Comment by fherrick** [comment]
From: Muhammad Bajwa 
Sent: Tuesday, May 05, 2015 4:17 PM
To: Aamir Sajjad; Tolga Koseoglu; Terry Krystian
Cc: Felicia Herrick
Subject: RE: Survey Application: browse access by watgsurvey.com not working

Hi Aamir,

We reverted some settings and removed the host headers on your development machine. Felicia & I have tested accessing the survey application from our computers and we can access it using the IP address. Let’s keep these settings until you are done and ready with a stable build of the application.

Once you give us the green signal that all items are complete and the survey App is ready to be migrated into staging, Tolga will help you deploy this application on Staging server.

That’s when we will get a friendly URL like http://itstaging.watg.com/survey

Thanks 
Muhammad Bajwa | Senior Director of Information Systems
WATG | designing destinations
300 Spectrum Center Drive, Suite 500 | Irvine, CA 92618  USA
+1 949 574 8500 tel
watg.com
From: Aamir Sajjad 
Sent: Tuesday, May 05, 2015 11:48 AM
To: Tolga Koseoglu; Terry Krystian
Cc: Felicia Herrick; Muhammad Bajwa
Subject: Survey Application: browse access by watgsurvey.com not working

Hi Tolga, Terry, 

I can access the survey application on (Machine IP Address 216.65.214.89) by watgssurvey.com, as I edited the host file. But I am not sure how Felicia can access outside the mentioned machine. Please guide how can I do it or take necessary actions by yourself. 

Feel free to write if you require more information from my side.


Regards,
Aamir

**Comment by fherrick** [comment]
using this url to send out surveys - http://public2.watg.com:80/survey/sample-questions---test-06242015
