### ISSUE TITLE
copied a closed survey - got error

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#33]
copied a closed survey, made no changes
went to the direct link for survey - http://192.168.1.8:80/survey/new-survey-Copy285217579
and got this error

![error](https://cloud.githubusercontent.com/assets/11509212/7359136/f04cc92c-ecef-11e4-981f-4d35160db436.png)

**Comment by fherrick** [comment]
For some reason I'm not able to access the survey site using the url I used previously  - have tried http://192.168.1.8/#/  - internal link to server and http://216.65.214.89/#/ external link to server.

Is the survey application still deployed?

**Comment by aamir-poswal** [comment]
@fherrick,

I can access the application using following url in dev server environment.

wtagsurvey.com

**Comment by fherrick** [comment]
Used http://192.168.1.8:80/survey/new-survey-copy-124900807 to test. Copied survey, closed it, reopened it. Worked fine.
