### ISSUE TITLE
fix mispelling in invitation email sent to users

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#36]
Can you change from Thanks, the wtag team' to Thank you, The WATG team.

![invitation](https://cloud.githubusercontent.com/assets/11509212/8320204/9bbc91a8-19cc-11e5-9f59-6e2eadade576.png)

The invitation sent from Create Survey, email tab needs to be updated as well.

Change to ' We invite you to take following survey' Also change url to 'http://public2.watg.com/ ' instead of localhost

![survey email](https://cloud.githubusercontent.com/assets/11509212/8339211/be20c694-1a6a-11e5-8e7e-1fb523b3e863.png)

**Comment by fherrick** [comment]
yes, url fixed and word 'to' added.
Would you also add 'the'  
Change to ' We invite you to take following survey' 

![email](https://cloud.githubusercontent.com/assets/11509212/8484258/7954878e-20ab-11e5-8d68-18b2ec4e99c8.png)

**Comment by aamir-poswal** [comment]
@fherrick ,

Please verify, and share your feedback.

**Comment by fherrick** [comment]
![email](https://cloud.githubusercontent.com/assets/11509212/8584599/2dfab2ae-258d-11e5-9a7c-fc7173f75af1.png)

fixed
