### ISSUE TITLE
created a multiple choice question and not able to add new choices when editing

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#37]
I create a new survey 'Sample Questions - Test 06/24/2015'. Added a multple choice question.
Added 3 choices. Chunky, Smooth and None. Only 2 of the choices were added, it lost the 3 choice. When I went to edit question was still not able to add 3rd choice.  Can you fix this please. Thanks

Using the http://public2.watg.com/#/survey site.

![new poll](https://cloud.githubusercontent.com/assets/11509212/8337097/b8a33ed4-1a5d-11e5-8a4e-1eb1c10c0cf3.png)

**Comment by aamir-poswal** [comment]
@fherrick ,

You need to click add choice button after entering third choice text to save the third choice. 
http://screencast.com/t/NKDEHxOsI

**Comment by fherrick** [comment]
yes, when creating the question this works but when I click edit - there is no option to add more choices? 

When creating a multiple choice question i have a button called 'Add Answer Choice'. That is not listed when I edit a multiple choice question

see screenshot
![edit](https://cloud.githubusercontent.com/assets/11509212/8483835/6d520d38-20a8-11e5-83de-368912178a43.png)

**Comment by aamir-poswal** [comment]
@fherrick ,

Please verify, and share your feedback.

**Comment by fherrick** [comment]
Yes, Now this is fixed. I see the add question when in edit mode
![edit mc](https://cloud.githubusercontent.com/assets/11509212/8584554/b1303370-258c-11e5-8fe2-d8899ba937fc.png)
