### ISSUE TITLE
close after certain date not working

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#38]
Set the close date for 'Sample Questions - Test 06/24/2015'/ survey to 6/26/2015 at 10:59am. 

![closed time](https://cloud.githubusercontent.com/assets/11509212/8337921/ab10b4fe-1a62-11e5-95b2-2a1c29e447f3.png)

Sent out this url for survey - http://public2.watg.com:80/survey/sample-questions---test-06242015
User was unable to access survey on 6/24/2015 at 11:15am pacific 
Got this message. 
![closed error](https://cloud.githubusercontent.com/assets/11509212/8337941/be8614f2-1a62-11e5-8314-50c6877b3b68.png)

**Comment by aamir-poswal** [comment]
@fherrick ,

Please verify, and share your feedback.

**Comment by fherrick** [comment]
Set the close date for 'test multiple pages' survey to 7/02/2015 at 11:00am.
![close](https://cloud.githubusercontent.com/assets/11509212/8483930/2d43df7c-20a9-11e5-885c-2e0582bcdef6.png)

tested on iphone not on WATG networked - no error, survey opened just fine.

**Comment by fherrick** [comment]
survey displayed closed message after the time
