### ISSUE TITLE
image attached to question is broken

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#39]
image attached to question is broken when user opens link to survey
survey link sent to users - http://public2.watg.com:80/survey/sample-questions---test-06242015

image from Create survey
![image](https://cloud.githubusercontent.com/assets/11509212/8337993/06571d1c-1a63-11e5-81de-07b73cdb9a1b.png)

user screenshot of survey - broken image
![user view](https://cloud.githubusercontent.com/assets/11509212/8338101/b3b722ea-1a63-11e5-8cbe-052ac35db4e6.png)

**Comment by aamir-poswal** [comment]
@fherrick ,

Please verify, and share your feedback.

**Comment by fherrick** [comment]
image that was broken is now displaying correctly
![Uploading comments removed.png…]()
