### ISSUE TITLE
Create Yes/No or True/False Question

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#4]
Each Survey can have multiple types of questions

Please create a simple yes/no or true/false question
1.User will enter a question
2. response will be yes/no or true/false

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15)

**Comment by fherrick** [comment]
survey crashes when testing the direct url

**Comment by aamir-poswal** [comment]
Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
This is done, Everything works

![1](https://cloud.githubusercontent.com/assets/11509212/7009023/3ffdba3a-dc4c-11e4-95dc-a7aaaaeb0f69.png)

![tf direct url2](https://cloud.githubusercontent.com/assets/11509212/7009011/1d9b0984-dc4c-11e4-9680-8c9d2426a524.png)
![tf direct url](https://cloud.githubusercontent.com/assets/11509212/7009013/1dc84bf6-dc4c-11e4-8f14-e62d69d97180.png)
