### ISSUE TITLE
 remove the port 80 from the url that is generated

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#41]
We noticed the direct link generated in collect response had port 80 specified. 

Can we remove the port 80 from the url that is generated for the survey

In short.. ( link should work without the port too)
http://public2.watg.com/survey/sample-questions---test-06242015

![link to survey](https://cloud.githubusercontent.com/assets/11509212/8389565/a9b8af00-1c27-11e5-958d-b6d581075ebf.png)

**Comment by aamir-poswal** [comment]
@fherrick ,

Please verify, and share your feedback.

**Comment by fherrick** [comment]
fixed

![url](https://cloud.githubusercontent.com/assets/11509212/8483455/a0ea0662-20a5-11e5-9ae3-4b6abf9df009.png)
