### ISSUE TITLE
The default text “user comments” and “long answer” should be removed. I

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#42]
The default text “user comments” and “long answer” should be removed from the survey. Instead it would be nice to have a character count appear with the answer box that shows the user on how many characters they are allowed to enter into the box.

![2015-06-27_044841](https://cloud.githubusercontent.com/assets/11509212/8389571/cdca79aa-1c27-11e5-89ea-43bbe063c4bb.png)

Not a priority at this time

**Comment by aamir-poswal** [comment]
@fherrick ,

Please verify, and share your feedback.

**Comment by fherrick** [comment]
default text was removed. The character count has not been added
![comments removed](https://cloud.githubusercontent.com/assets/11509212/8483493/d0f7ce2a-20a5-11e5-82d0-ef5136bc5167.png)

**Comment by aamir-poswal** [comment]
@fherrick ,

Please verify, and share your feedback.
