### ISSUE TITLE
change closed survey message

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#44]
Change from 'Thank you, we have already counted your response'

Change to 'Thank you, we have received your response'

**Comment by aamir-poswal** [comment]
@fherrick ,

Please verify, and share your feedback.

**Comment by fherrick** [comment]
Please remove the word 'already' from message that appears when block by cookie is turned on.

![1](https://cloud.githubusercontent.com/assets/11509212/8807733/46c45aaa-2f93-11e5-897b-f850fa068ea3.png)

**Comment by aamir-poswal** [comment]
@fherrick ,

Please verify, and share your feedback.

**Comment by fherrick** [comment]
Done
![1](https://cloud.githubusercontent.com/assets/11509212/9885892/7344b5d6-5b9c-11e5-9a69-91e16ac960b2.png)
