### ISSUE TITLE
error message when using create/invite user

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#45]
Tried to add Naveed Khan, nkhan@watg.com as a user and got the attached error message.

![1](https://cloud.githubusercontent.com/assets/11509212/8807514/e2b4ab38-2f91-11e5-888c-21bfc57b3d2a.png)

**Comment by aamir-poswal** [comment]
@fherrick ,

Email sent to Tolga and Terry for resolution help.

**Comment by fherrick** [comment]
I was able to create and invite a new user. See email received below.
![email](https://cloud.githubusercontent.com/assets/11509212/8944779/69121382-3537-11e5-89ce-b63571bf5dff.png)
