### ISSUE TITLE
error submitting survey in IE

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#46]
I completed this survey - http://public2.watg.com/survey/9. and got the attached error message

![1](https://cloud.githubusercontent.com/assets/11509212/8944436/9748040c-3535-11e5-9d82-7e7bfeebc856.jpg)

also completed survey on iphone not on watg network - and got the same error after hitting submit

Survey was copied from 'Test Survey part 2 Copy'

**Comment by aamir-poswal** [comment]
@fherrick ,

Requested help from Tolga and Terry to resolve this issue.

**Comment by fherrick** [comment]
From: Muhammad Bajwa 
Sent: Monday, August 03, 2015 11:23 AM
To: Aamir; Tolga Koseoglu
Cc: Felicia Herrick; Naveed Khan; Terry Krystian
Subject: RE: [SurveyTrackerApp] error submitting survey in IE (#46)

Hi Aamir,

The workaround seems to have worked based on my initial testing. I was able to submit the responses for a survey this morning. Thanks

One thing I noticed while trying to access the survey from my iPhone. It seems to be chopping off the webpage from the left side.(screenshot attached) Notice how the text on the left side of the webpage is not showing correctly. Can you check on your smartphone. The survey in question is at the following link.
http://public2.watg.com/survey/2

Muhammad Bajwa | Senior Director of Information Systems
WATG | designing destinations
300 Spectrum Center Drive, Suite 500 | Irvine, CA 92618  USA
+1 949 574 8500 tel
watg.com

**Comment by fherrick** [comment]
Removed the Host and now we are able to submit the survey with no error.
