### ISSUE TITLE
webpage is being chopped off in iphone.

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#47]
One thing I noticed while trying to access the survey from my iPhone. It seems to be chopping off the webpage from the left side.(screenshot attached) Notice how the text on the left side of the webpage is not showing correctly. Can you check on your smartphone. The survey in question is at the following link.
http://public2.watg.com/survey/2

![img_5211](https://cloud.githubusercontent.com/assets/11509212/9074982/9129f618-3ac4-11e5-8986-29072fc9ae7e.png)

**Comment by mobajwa** [comment]
lets add some padding on the left of the page to fix this issue.

**Comment by mobajwa** [comment]
@aamir-poswal  The new build is much better but it still has padding issues in a couple of spots. (screenshot attached) 
![2015-08-20_161610](https://cloud.githubusercontent.com/assets/3451741/9399318/6d5dd27c-4767-11e5-89a9-f5023788ddb7.png)

**Comment by mobajwa** [comment]
We can fix these issues in Version 2.0

**Comment by fherrick** [comment]
surveys have been displaying ok on iphone
