### ISSUE TITLE
Create a Free Text Answer/Question

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#5]
Each Survey can have multiple types of questions

Please create a free text answer/question
1. User will enter a question
2. Response will be an option of short answer or long answer.
3. would be nice if user can input the character limit to use for answer

![free text](https://cloud.githubusercontent.com/assets/11509212/6676042/2c41f616-cbe2-11e4-81b0-e5ff69435bd7.jpg)

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15)

**Comment by fherrick** [comment]
survey crashes when testing the direct url

**Comment by aamir-poswal** [comment]
Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
Character limit for short answer doesn't appear to work.
![limit](https://cloud.githubusercontent.com/assets/11509212/7009163/23540302-dc4d-11e4-9a2f-7046d4fc6cbe.png)
  

![limit2](https://cloud.githubusercontent.com/assets/11509212/7009197/553b7d3c-dc4d-11e4-8a2a-125af407b16a.png)
![limit3](https://cloud.githubusercontent.com/assets/11509212/7009218/80969372-dc4d-11e4-9176-9ae0892fa3bd.png)

**Comment by aamir-poswal** [comment]
@fherrick, Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
short answer limit of 10 characters worked and 100 answer limit worked on long
![1](https://cloud.githubusercontent.com/assets/11509212/7288259/a40fbe46-e913-11e4-92e5-17304c4443a3.png)
