### ISSUE TITLE
Open items to be fixed

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#56]
Testing Survey
•         I tried to create a survey and it gives an error (screenshot attached)
•         http://216.65.214.89/surveytakerapp/survey/5
•         I got an error when creating questions in the survey. (screenshot attached)

**Comment by fherrick** [comment]
-Was able to create a survey
-able to add questions with no errors

**Comment by fherrick** [comment]
Got an error when accessing survey from inside and outside the network-  link http://216.65.214.89/SurveyTakerApp/survey/7
error when 
![1](https://cloud.githubusercontent.com/assets/11509212/9860438/04d8b36a-5ae1-11e5-9ee4-3bee8ece4cec.png)

**Comment by aamir-poswal** [comment]
@fherrick 

Please verify now, and share your feedback.

**Comment by fherrick** [comment]
Able to access survey, with no error message

**Comment by aamir-poswal** [comment]
Please verify, and share your feedback.

**Comment by fherrick** [comment]
this has been fixed
