### ISSUE TITLE
browser tab title

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#57]
The browser tab says WATG Survey when user goes to survey but when it is submitted it changes to the ip address. Browser tab title should remain WATG Survey.

![tab title](https://cloud.githubusercontent.com/assets/11509212/9884741/497e0b86-5b96-11e5-8d27-e5165a92afc7.png)

**Comment by aamir-poswal** [comment]
Please verify, and share your feedback.

**Comment by fherrick** [comment]
Now tab say success when survey has been submitted

![10](https://cloud.githubusercontent.com/assets/11509212/9921208/fac5ca88-5c8f-11e5-9913-f12a6c072fd8.png)
