### ISSUE TITLE
error when I clicked on Poll, Questions

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#59]
error when I clicked on Poll, Questions 
Tried to add multiple choice question and it disappeared when I clicked save.
![error](https://cloud.githubusercontent.com/assets/11509212/9885564/9fd9e7ee-5b9a-11e5-8f50-90c84b197065.jpg)

**Comment by fherrick** [comment]
Screenshots of trying to add question and error
![1](https://cloud.githubusercontent.com/assets/11509212/9885707/846d1fde-5b9b-11e5-8b7f-c08285c6f2e1.png)
![2](https://cloud.githubusercontent.com/assets/11509212/9885710/877e265a-5b9b-11e5-81ef-2283ab9a7527.png)
![3](https://cloud.githubusercontent.com/assets/11509212/9885712/8a1d5d68-5b9b-11e5-9ea8-d920d58004df.png)

**Comment by aamir-poswal** [comment]
@fherrick ,

It is resolved. Please verify, and share your feedback.

**Comment by fherrick** [comment]
yes, i was able to create a new poll, add questions with no errors
