### ISSUE TITLE
Open issues for Poll

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#60]
Testing Polls
•         Email I received said that "There is a new response to the Ice Cream Flavor 123 survey." It should have said "Poll" at the end .
•         Also, Webpage title said survey as well.
•         The block by Cookie is not working as I was able to submit multiple entries while I was in same browsing session in chrome.

**Comment by aamir-poswal** [comment]
@fherrick ,

Please verify, and share your feedback.

**Comment by fherrick** [comment]
- email now says poll at the end.
![untitled](https://cloud.githubusercontent.com/assets/11509212/9921171/a28e2716-5c8f-11e5-9efd-5254534367e5.png)

- webpage tab says Poll now

![untitled](https://cloud.githubusercontent.com/assets/11509212/9921098/0bcec7fe-5c8f-11e5-9d55-c16de4b45049.png)

- Got a message when trying to retake poll
![untitled](https://cloud.githubusercontent.com/assets/11509212/9921116/43dfd3d6-5c8f-11e5-84a9-35da618fc312.png)
