### ISSUE TITLE
Create a rating scale answer/question

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#7]
Each Survey can have multiple types of questions

Please create a rating scale answer/question
1. User will enter multiple questions. Max is 10 questions
2. Response will be a range of  answers 1-5 or 1-10, selected by survey creator

sample images
![scale](https://cloud.githubusercontent.com/assets/11509212/6676204/5b91d46c-cbe3-11e4-921e-bb73691d7d5c.png)

![scale1](https://cloud.githubusercontent.com/assets/11509212/6676236/a66991d2-cbe3-11e4-9b7c-c98ba34734f7.png)

![scale2](https://cloud.githubusercontent.com/assets/11509212/6676253/bd94de3e-cbe3-11e4-8243-e5f1de86ace0.png)

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15)

**Comment by fherrick** [comment]
Was not able to add a question for the rating. Also after I clicked save for rating scale Question 1 was removed completely.
![4](https://cloud.githubusercontent.com/assets/11509212/6908487/2a761e3c-d6f2-11e4-8382-793b25380e6a.png)
screenshot after I clicked save to add rating scale question
![5](https://cloud.githubusercontent.com/assets/11509212/6908502/50d3edde-d6f2-11e4-91fe-b660129d1c6e.png)

**Comment by aamir-poswal** [comment]
Please verify now, and share your feedback.

http://screencast.com/t/3EijfrFixy5z

**Comment by fherrick** [comment]
This is not how we want the rating scale to work.

When i select rating scale, it is automatically adding the scale but not allowing the user to enter text for a question. 
![1](https://cloud.githubusercontent.com/assets/11509212/6931997/a3c003f8-d7c8-11e4-9025-f7dd2f79a5e3.png)


Also we want the rating scale to look like this:

![scale](https://cloud.githubusercontent.com/assets/11509212/6676204/5b91d46c-cbe3-11e4-921e-bb73691d7d5c.png)

![scale1](https://cloud.githubusercontent.com/assets/11509212/6676236/a66991d2-cbe3-11e4-9b7c-c98ba34734f7.png)

![scale2](https://cloud.githubusercontent.com/assets/11509212/6676253/bd94de3e-cbe3-11e4-8243-e5f1de86ace0.png)

**Comment by aamir-poswal** [comment]
@fherrick Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
@aamir-poswal , @mbajwa 
Rating looks much better.  2 issues that i can find - for some reason when i try to add 5 questions, the last question is dropped off and not added.

Build Survey - trying to add 5 questions to rating
![rank5](https://cloud.githubusercontent.com/assets/11509212/7010610/70f0f7e6-dc57-11e4-9b81-7a746ab9bcaa.png)

After save - 5th question was not added.
![rank6](https://cloud.githubusercontent.com/assets/11509212/7010620/8295aa8c-dc57-11e4-95db-9021052fe939.png)

**Comment by fherrick** [comment]
@aamir-poswal @mbajwa 
When editing a rating question, how do I add additional questions. I do no see an option under edit.
![rank2](https://cloud.githubusercontent.com/assets/11509212/7010645/c4f15f52-dc57-11e4-8878-8dd4f0b8d3f5.png)

**Comment by fherrick** [comment]
@aamir-poswal 
Mandatory Question is not working when selected, survey let me submit with none of the rating selected.

![mandatory](https://cloud.githubusercontent.com/assets/11509212/7010697/16d2991c-dc58-11e4-9fcd-5e691ba9ebca.png)

**Comment by aamir-poswal** [comment]
@fherrick, Please verify on dev, and share your feedback.

**Comment by aamir-poswal** [comment]
@fherrick, 

Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
Able to edit and add another question to rating
![1](https://cloud.githubusercontent.com/assets/11509212/7359262/48360184-ecf1-11e4-8da8-54374da8b3a6.png)

**Comment by fherrick** [comment]
Before editing  - only 2 questions
![1](https://cloud.githubusercontent.com/assets/11509212/7359494/e2f8c5ba-ecf3-11e4-9d73-57dda1ec5c31.png)

Try to edit and add 2 additional questions
Its not saving the 2 questions I just added.
![edit](https://cloud.githubusercontent.com/assets/11509212/7359569/8397f6c6-ecf4-11e4-871f-e1d715778a69.png)


![after edit](https://cloud.githubusercontent.com/assets/11509212/7359576/a1985b34-ecf4-11e4-9e6e-ba0fee578e78.png)

**Comment by fherrick** [comment]
Yes, now able to edit/add questions.
