### ISSUE TITLE
Create a new Survey Page

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#8]
Create a new Survey Page

This would be the first screen a user would see when they are creating a new survey.
After this screen is completed the user would go to the survey edit/question page.

1. Field for Survey name/Title  - creator should enter the Survey name/title
2. Text field for survey start message or description
3. text Field for survey completed - message to be displayed after participant hits submit button
4. Survey options could be on this page maybe or the build survey page.
     - show progress indicator
     - show back button

sample images - 
![start page](https://cloud.githubusercontent.com/assets/11509212/6676378/8d5546a4-cbe4-11e4-85c7-64538e227e7e.png)

![language](https://cloud.githubusercontent.com/assets/11509212/6678424/e75a7fd0-cbf7-11e4-8f0d-122ad697f696.png)

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15)

**Comment by fherrick** [comment]
When I created a new survey and clicked save, it took me to the all surveys page.  Instead of going o the all surveys list, please go to the create survey screen with the survey settings, questions, other options tabs
![3](https://cloud.githubusercontent.com/assets/11509212/6908346/3eb8240e-d6f1-11e4-85da-9ee465be7404.png)

![2](https://cloud.githubusercontent.com/assets/11509212/6908347/3ebcace0-d6f1-11e4-9bbf-e35a0c2265c8.png)

**Comment by aamir-poswal** [comment]
Please verify now, and share your feedback.

**Comment by fherrick** [comment]
The custom start message should appear at the beginning of the survey. Not able to see message after survey is completed. Got an error

![1](https://cloud.githubusercontent.com/assets/11509212/6932066/3ef3d69c-d7c9-11e4-951e-8116e379afad.png)

![2](https://cloud.githubusercontent.com/assets/11509212/6932067/421d3912-d7c9-11e4-9970-1f3d4b5043eb.png)

![error](https://cloud.githubusercontent.com/assets/11509212/6932080/658ccfca-d7c9-11e4-8a09-ddc9cb2953d0.png)

**Comment by fherrick** [comment]
not able to test if these options are working yet.

https://github.com/aamir-poswal/SurveyTrackerApp/issues/25

**Comment by aamir-poswal** [comment]
Please verify on dev, and share your feedback.

**Comment by fherrick** [comment]
Yes, now it goes directly to create survey after creating new survey.
