### ISSUE TITLE
Ability to set the survey question as mandatory

### ISSUE THREAD

**Issue by fherrick** [aamir-poswal/SurveyTrackerApp#9]
Please create an option on each question that makes answer the question mandatory. 
A check box the survey creator can select.

If the question is not answered, then the user will not be able to submit/finish the survey.

Would be great if creator can enter their own error message. 
If not then Display an error message 'Please review your answers for this page, there was a problem with one or more of them.'

![multiple choice](https://cloud.githubusercontent.com/assets/11509212/6676546/fd7f49c4-cbe5-11e4-9f37-db0128785afa.png)

![mandatory](https://cloud.githubusercontent.com/assets/11509212/6676591/60f7d57a-cbe6-11e4-97de-dacf8293fdbf.png)

![mandatory 1](https://cloud.githubusercontent.com/assets/11509212/6676750/7670889c-cbe7-11e4-9d69-841686500a33.png)

**Comment by mbajwa** [comment]
This is a level 1 priority (03/24/15)

**Comment by fherrick** [comment]
This is working
